version = 3.10.3
runner.dialect = scala3
maxColumn = 80
assumeStandardLibraryStripMargin = true
align.preset = none
align.stripMargin = true

newlines.source = keep
newlines.avoidForSimpleOverflow = []
newlines.ignoreInSyntax = false
newlines.inInterpolation = avoid

binPack.literalArgumentLists = false
binPack.parentConstructors = never
binPack.importSelectors = unfold

optIn.configStyleArguments = true
danglingParentheses.preset = true
verticalMultiline.atDefnSite = true

project {
  git = true
  excludeFilters = [
    bench/corpus
    test/resources
    "semanticdb/.*"
    "openapi-client/src/main/scala/.*/generated/.*"
  ]
  layout = StandardConvention
}

rewrite {
  rules = [
    AvoidInfix,
    Imports,
    RedundantBraces,
    RedundantParens,
    SortModifiers,
    RemoveSemicolons
  ]
  trailingCommas.style = always
  imports {
    expand = true
    removeRedundantSelectors = true
    sort = ascii
    groups = [
      ["scala\\.meta\\..*", "org\\.scalameta\\..*"],
      ["sbt\\..*"],
      ["java.?\\..*"],
      ["scala\\..*"],
      ["org\\..*"],
      ["com\\..*"]
    ]
  }
  redundantBraces {
    preset = all
    oneStatApply {
      parensMaxSpan = 300
      bracesMinSpan = 300
    }
  }
  redundantParens.preset = all
  sortModifiers.preset = styleGuide
}
